micronaut:
  application:
    name: java-concurrency-sample-mvn

datasources:
  default:
    url: jdbc:h2:~/.antoniocaccamo/db/java-concurrency-sample;DB_CLOSE_DELAY=5;DB_CLOSE_ON_EXIT=TRUE
#    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver

app:
  file: files/users.txt
  dir : target
  schedule:
    time-unit : "SECONDS"
    delay : 5
    period: 10

flyway:
  datasources:
    default:
      locations: classpath:migration
